version: '2'
services:
    lsbtest-app:
        image: lsbtest
        external_links:
            - lsbtest-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/LSBTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lsbtest-postgresql:
        extends:
            file: postgresql.yml
            service: lsbtest-postgresql
